version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
  backend:
    build: ./backend
    env_file:
      - ./backend/app/.env
    ports:
      - "4000:8081"