import Head from 'next/head'
import React from 'react';
import Image from 'next/image'
import Layout from '../components/Layout';
import styles from '../styles/Home.module.css'
import Link from 'next/link';
import data from '../utils/sample_data';

export default function Home({ data }) {
  return (
    <Layout title='Home Page'>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        courses:
        <ul>
        { data.map((course) => (
          <div key={course.course_name}>
            <Link href={`/course/${course.course_name}`}><a><li key={course.course_name}> {course.course_name} </li></a></Link>
          </div>
        )) }
        </ul>
      </div>
    </Layout>
  )
}

export async function getServerSideProps() {
  
  return {
    props: {
      data: data.courses,
    },
  };
}
